name: Receive and Release EXE

on:
  repository_dispatch:
    types: [exe_update]

permissions:
  contents: write

jobs:
  update_exe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare folders
        run: mkdir -p bin

      - name: Download EXE from build repo release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.client_payload.version }}
          EXE_NAME: ${{ github.event.client_payload.exe_name }}
          REPO_NAME: ${{ github.event.client_payload.release_repo }}  # e.g. "JobAssignment"
          OWNER: DaSonOfPoseidon
        run: |
          echo "Downloading $EXE_NAME version $VERSION from $OWNER/$REPO_NAME release"
          URL="https://api.github.com/repos/$OWNER/$REPO_NAME/releases/tags/$VERSION"
          ASSET_URL=$(curl -s $URL | jq -r ".assets[] | select(.name==\"$EXE_NAME\") | .url")
          if [ -z "$ASSET_URL" ]; then
            echo "Asset not found in release"
            exit 1
          fi
          curl -L -H "Accept: application/octet-stream" -H "Authorization: token $GITHUB_TOKEN" -o ./bin/$EXE_NAME $ASSET_URL

      - name: Commit updated exe
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add bin/${{ github.event.client_payload.exe_name }}
          git commit -m "Update ${{ github.event.client_payload.exe_name }} to ${{ github.event.client_payload.version }}" || echo "No changes to commit"
          git push origin main

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.client_payload.version }}
          name: Release ${{ github.event.client_payload.version }}
          body: Automated release of ${{ github.event.client_payload.exe_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/${{ github.event.client_payload.exe_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
